name: Publish

on: 
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Compare Versions
        run: |
          oldver=$(npm info cs-crypto version) newver=$(node -p "require('./package.json').version"); [ $oldver != $newver ] && \
          echo 'version_changed=true' >> $GITHUB_ENV; exit 0
      - name: Use Authentication Token
        if: env.version_changed == 'true'
        run: echo '//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}' > .npmrc
      - name: Install
        if: env.version_changed == 'true'
        run: yarn install
      - name: Run Tests
        if: env.version_changed == 'true'
        run: yarn run test
      - name: Publish to NPM
        if: env.version_changed == 'true'
        run: yarn publish
