name: Tests

on: 
  push:
    branches:
      - master
    paths:
      - 'src/**'
  pull_request:
    branches:
      - master
    paths:
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn install
      - name: Build
        run: yarn run build
      - name: Run Tests
        run: yarn run test
